name: babelcore
region: nyc
services:
  - name: web
    github:
      repo: TerranceFinleyZ/Babelcore_AI_search_Library-
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CLERK_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: GROQ_MODEL
        scope: RUN_AND_BUILD_TIME
        value: llama-3.1-8b-instant
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        scope: RUN_AND_BUILD_TIME
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        scope: RUN_AND_BUILD_TIME
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
        scope: RUN_AND_BUILD_TIME
        value: /search
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
        scope: RUN_AND_BUILD_TIME
        value: /search
domains:
  - domain: babelcore.net
    type: PRIMARY
