name: babelcore
region: nyc
services:
  - name: web
    github:
      repo: TerranceFinleyZ/Babelcore_AI_search_Library-
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    http_port: 3000
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CLERK_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
domains:
  - domain: babelcore.net
    type: PRIMARY
